"""empty message

Revision ID: a71d8080d008
Revises: f511222c40f9
Create Date: 2025-05-10 00:09:51.262766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71d8080d008'
down_revision: Union[str, None] = 'f511222c40f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_path', sa.String(length=255), nullable=True))
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('teams', 'logo_path')
    # ### end Alembic commands ###
