"""empty message

Revision ID: f511222c40f9
Revises: 
Create Date: 2025-05-09 23:47:39.821815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f511222c40f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_captain_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('is_roblox_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('roblox_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roblox_username')
    op.drop_column('users', 'is_roblox_verified')
    op.drop_column('teams', 'team_captain_id')
    # ### end Alembic commands ###
